version: '2'
services:
    taskmaster-app:
        image: taskmaster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://taskmaster-mysql:3306/taskmaster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8091:8091
    taskmaster-mysql:
        extends:
            file: mysql.yml
            service: taskmaster-mysql
